development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>/1


test:
  adapter: test
  url: <%= ENV["REDIS_URL"] %>/2

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: monte_cinema_api_production
